version: '3.5'

services:
  db:
    image: kapua/kapua-sql:1.0.3
    ports:
      - 8181:8181
      - 3306:3306

  es:
    image: elasticsearch:5.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
    volumes:
      - es-storage:/usr/share/elasticsearch/data

  events-broker:
    image: kapua/kapua-events-broker:1.0.3
    ports:
      - 5672:5672

  broker:
    image: kapua/kapua-broker:1.0.3
    ports:
      - 1883:1883
      - 61614:61614
    depends_on:
      - db
      - es
      - events-broker

  kapua-console:
    image: kapua/kapua-console:1.0.3
    ports:
      - 8080:8080
    depends_on:
      - broker
      - db
      - es
      - events-broker

  kapua-api:
    image: kapua/kapua-api:1.0.3
    ports:
      - 8081:8080
    depends_on:
      - broker
      - db
      - es
      - events-broker

  kura-simulator:
    image: kapua/kura-simulator:2017-07-28
    environment:
      - KSIM_BASE_NAME=sim-
      - KSIM_ACCOUNT_NAME=kapua-sys
      - KSIM_NUM_GATEWAYS=1
      - KSIM_BROKER_USER=kapua-broker
      - KSIM_BROKER_PASSWORD=kapua-password
      - KSIM_BROKER_PROTO=tcp
      - KSIM_BROKER_HOST=broker
      - KSIM_BROKER_PORT=1883
      - KSIM_SIMULATION_URL=/data/model.json
    entrypoint:
      - /bin/sh
      - -c
      - |
          sleep 30s
          java \
            -Dlogback.configurationFile=/opt/kapua-simulator-kura/logback.xml \
            -cp /opt/kapua-simulator-kura/kapua-simulator-kura-0.3.0-SNAPSHOT-app.jar \
            org.eclipse.kapua.kura.simulator.main.SimulatorRunner
    depends_on:
      - broker
      - db
      - es
      - events-broker
    volumes:
      - ./:/data

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    depends_on:
      - es

volumes:
  es-storage: null
  grafana-storage: null
